// <auto-generated />
using System;
using AssetSalesApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetSalesApp.Data.Migrations
{
    [DbContext(typeof(AssetSalesDbContext))]
    partial class AssetSalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AssetSalesApp.Data.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InUse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAcquired = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = true,
                            Location = "Location1",
                            Name = "Asset1",
                            PurchasePrice = 1234.0
                        },
                        new
                        {
                            Id = 2,
                            DateAcquired = new DateTime(2022, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = false,
                            Location = "Location2",
                            Name = "Asset2",
                            PurchasePrice = 4321.0
                        },
                        new
                        {
                            Id = 3,
                            DateAcquired = new DateTime(2022, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = true,
                            Location = "Location3",
                            Name = "Asset3",
                            PurchasePrice = 2345.0
                        },
                        new
                        {
                            Id = 4,
                            DateAcquired = new DateTime(2022, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = true,
                            Location = "Location4",
                            Name = "Asset4",
                            PurchasePrice = 5432.0
                        },
                        new
                        {
                            Id = 5,
                            DateAcquired = new DateTime(2022, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = false,
                            Location = "Location5",
                            Name = "Asset5",
                            PurchasePrice = 3456.0
                        },
                        new
                        {
                            Id = 6,
                            DateAcquired = new DateTime(2022, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = true,
                            Location = "Location6",
                            Name = "Asset6",
                            PurchasePrice = 6543.0
                        },
                        new
                        {
                            Id = 7,
                            DateAcquired = new DateTime(2022, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InUse = false,
                            Location = "Location7",
                            Name = "Asset7",
                            PurchasePrice = 4567.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
